import os
from typing import Union, List


class TransducerFile:
    def __init__(self, path: Union[str, os.PathLike[str]]) -> None: ...
    def lookup(self, string: str) -> List[str]: ...
    def symbol_count(self) -> int: ...
