# typings for cython module: _hfstol (source in _hfst_optimized_lookup.pyx)
import os
from typing import Union, List, Set, Dict, Iterable

class PyTransducerFile:
    def __init__(self, path: Union[str, os.PathLike[str]]) -> None: ...
    def lookup(self, string: str) -> List[str]: ...
    def lookup_symbols(self, string: str) -> List[List[str]]: ...
    def bulk_lookup(self, strings: Iterable[str]) -> Dict[str, Set[str]]: ...
    def symbol_count(self) -> int: ...
