on:
  pull_request:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '05 16 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python: [3.9]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - run: pip install pipenv

      - run: pipenv install --dev

      - run: pipenv run make test
